openapi: 3.0.3
info:
  title: DRF ECOMMERCE API
  version: 1.0.0
  description: This is an ecommerce API buit with django and djangorestframework
paths:
  /api/brand/:
    get:
      operationId: api_brand_list
      description: API endpoint that allows brands to be viewed or edited.
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Brand'
          description: ''
  /api/category/:
    get:
      operationId: api_category_list
      description: API endpoint that allows categories to be viewed or edited.
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
          description: ''
  /api/product/:
    get:
      operationId: api_product_list
      description: API endpoint that allows products to be viewed or edited.
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          description: ''
components:
  schemas:
    Brand:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
      required:
      - id
      - name
    Category:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        lft:
          type: integer
          readOnly: true
        rght:
          type: integer
          readOnly: true
        tree_id:
          type: integer
          readOnly: true
        level:
          type: integer
          readOnly: true
        parent:
          type: integer
          nullable: true
      required:
      - id
      - level
      - lft
      - name
      - rght
      - tree_id
    Product:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        brand:
          $ref: '#/components/schemas/Brand'
        category:
          type: string
          readOnly: true
        name:
          type: string
          maxLength: 200
        description:
          type: string
        is_digital:
          type: boolean
      required:
      - brand
      - category
      - id
      - name
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
